# https://taskfile.dev
version: '3'
vars:
  GREETING: Hello, World!
tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  nvim-sync:
    cmds:
      - cp -r ~/.dotfiles/config/nvim/* ~/.config/nvim
  sync:
    cmds:
      - cp -r ~/.dotfiles/config/* ~/.config/
